from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
CALC_DIR = ROOT / "calculations"
DOCS_DIR = ROOT / "docs"
DECKS_DIR = DOCS_DIR / "decks"


def load_library() -> dict[str, Any]:
    path = DATA_DIR / "molecules.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def atom_lines(geometry: list[list[Any]]) -> str:
    lines = []
    for atom in geometry:
        element, x, y, z = atom
        lines.append(f"{element:2s}  {x: .10f}  {y: .10f}  {z: .10f}")
    return "\n".join(lines)


def xyz_text(name: str, geometry: list[list[Any]]) -> str:
    lines = [str(len(geometry)), f"{name} generated by MO Atlas"]
    lines.extend(atom_lines(geometry).splitlines())
    return "\n".join(lines) + "\n"


def find_program(program_name: str, env_name: str | None = None) -> str:
    if env_name:
        env_value = os.environ.get(env_name)
        if env_value:
            return env_value

    found = shutil.which(program_name)
    if found:
        return found

    exe_name = program_name + ".exe"
    found = shutil.which(exe_name)
    if found:
        return found

    raise FileNotFoundError(
        f"Could not find {program_name}. Add C:\\orca to PATH, "
        f"or set the environment variable {env_name}."
    )


def write_orca_input(
    molecule_id: str,
    spec: dict[str, Any],
    work_dir: Path,
    nprocs_override: int | None = None
) -> Path:
    calc = spec["calculation"]
    keywords = calc.get("keywords", f"{calc['method']} {calc['basis']} TightSCF XYZFile")

    nprocs = int(nprocs_override or calc.get("nprocs", 1))
    maxcore = int(calc.get("maxcore", 1000))

    charge = int(spec.get("charge", 0))
    multiplicity = int(spec.get("multiplicity", 1))

    text = []
    text.append(f"! {keywords}")
    text.append("")
    text.append(f"%maxcore {maxcore}")

    if nprocs > 1:
        text.append("")
        text.append("%pal")
        text.append(f"  nprocs {nprocs}")
        text.append("end")

    text.append("")
    text.append(f"* xyz {charge} {multiplicity}")
    text.append(atom_lines(spec["geometry"]))
    text.append("*")
    text.append("")

    inp_path = work_dir / f"{molecule_id}.inp"
    inp_path.write_text("\n".join(text), encoding="utf-8")
    return inp_path


def run_orca(inp_path: Path, out_path: Path) -> None:
    orca = find_program("orca", "ORCA_EXE")

    with out_path.open("w", encoding="utf-8", errors="replace") as out:
        result = subprocess.run(
            [orca, inp_path.name],
            cwd=inp_path.parent,
            stdout=out,
            stderr=subprocess.STDOUT,
            text=True
        )

    if result.returncode != 0:
        raise RuntimeError(
            f"ORCA returned code {result.returncode}. "
            f"Check the output file: {out_path}"
        )


def parse_orbital_energies(out_path: Path) -> list[dict[str, Any]]:
    text = out_path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()

    orbitals: list[dict[str, Any]] = []
    inside = False

    pattern = re.compile(
        r"^\s*(\d+)\s+"
        r"([0-9]+\.[0-9]+)\s+"
        r"(-?[0-9]+\.[0-9]+)\s+"
        r"(-?[0-9]+\.[0-9]+)"
    )

    for line in lines:
        if "ORBITAL ENERGIES" in line:
            inside = True
            continue

        if inside and "MOLECULAR ORBITALS" in line:
            break

        if not inside:
            continue

        m = pattern.match(line)
        if not m:
            continue

        orbitals.append(
            {
                "orca_number": int(m.group(1)),
                "occupation": float(m.group(2)),
                "energy_hartree": float(m.group(3)),
                "energy_ev": float(m.group(4))
            }
        )

    if not orbitals:
        raise RuntimeError(
            "Could not parse orbital energies. "
            "Check whether the ORCA run finished normally."
        )

    return orbitals


def determine_homo_lumo(orbitals: list[dict[str, Any]]) -> tuple[int | None, int | None]:
    occupied = [o for o in orbitals if o["occupation"] > 0.0]

    if not occupied:
        return None, None

    homo = occupied[-1]["orca_number"]

    virtuals = [o for o in orbitals if o["orca_number"] > homo and o["occupation"] == 0.0]
    lumo = virtuals[0]["orca_number"] if virtuals else None

    return homo, lumo


def orbital_role(orca_number: int, homo: int | None, lumo: int | None) -> str:
    if homo is not None and orca_number == homo:
        return "HOMO"
    if lumo is not None and orca_number == lumo:
        return "LUMO"
    if homo is not None and orca_number < homo:
        return "occupied"
    if lumo is not None and orca_number > lumo:
        return "virtual"
    return "orbital"


def run_orca_plot_one(
    work_dir: Path,
    gbw_path: Path,
    orca_number: int,
    grid: int
) -> Path:
    orca_plot = find_program("orca_plot", "ORCA_PLOT_EXE")

    # Remove stale cube files for this orbital, so we can identify the new output.
    for old in work_dir.glob(f"{gbw_path.stem}.mo{orca_number}*.cube"):
        old.unlink()

    # ORCA MOs are numbered from 0.
    # Operator 0 is the alpha/single RHF-RKS operator.
    #
    # Menu sequence:
    # 2 -> enter MO number
    # 3 -> operator
    # 4 -> grid intervals
    # 5 -> output format, 7 = Gaussian cube
    # 8 -> MO rather than AO
    # 11 -> generate
    # 12 -> exit
    menu_input = "\n".join(
        [
            "2",
            str(orca_number),
            "3",
            "0",
            "4",
            str(grid),
            "5",
            "7",
            "8",
            "0",
            "11",
            "12",
            ""
        ]
    )

    result = subprocess.run(
        [orca_plot, gbw_path.name, "-i"],
        cwd=work_dir,
        input=menu_input,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        errors="replace"
    )

    log_path = work_dir / f"orca_plot_mo_{orca_number}.log"
    log_path.write_text(result.stdout, encoding="utf-8", errors="replace")

    candidates = sorted(
        work_dir.glob(f"{gbw_path.stem}.mo{orca_number}*.cube"),
        key=lambda p: p.stat().st_mtime,
        reverse=True
    )

    if not candidates:
        # Fallback: look at any cube file recently made.
        candidates = sorted(
            work_dir.glob("*.cube"),
            key=lambda p: p.stat().st_mtime,
            reverse=True
        )

    if not candidates:
        raise RuntimeError(
            f"orca_plot did not produce a cube file for MO {orca_number}. "
            f"Check {log_path}."
        )

    return candidates[0]


def update_deck_index(molecule_id: str, manifest: dict[str, Any]) -> None:
    DECKS_DIR.mkdir(parents=True, exist_ok=True)
    index_path = DECKS_DIR / "index.json"

    if index_path.exists():
        index = json.loads(index_path.read_text(encoding="utf-8"))
    else:
        index = {"decks": []}

    decks = [d for d in index["decks"] if d["id"] != molecule_id]
    decks.append(
        {
            "id": molecule_id,
            "name": manifest["name"],
            "formula": manifest["formula"],
            "point_group": manifest.get("symmetry", {}).get("point_group", ""),
            "manifest": f"{molecule_id}/manifest.json"
        }
    )

    decks.sort(key=lambda d: d["name"])
    index["decks"] = decks

    index_path.write_text(
        json.dumps(index, indent=2, ensure_ascii=False),
        encoding="utf-8"
    )


def build_deck(
    molecule_id: str,
    run_calculation: bool,
    export_cubes: bool,
    nprocs: int | None
) -> None:
    library = load_library()
    molecules = library["molecules"]

    if molecule_id not in molecules:
        known = ", ".join(sorted(molecules))
        raise KeyError(f"Unknown molecule {molecule_id!r}. Known molecules: {known}")

    spec = molecules[molecule_id]
    calc = spec["calculation"]

    work_dir = CALC_DIR / molecule_id
    work_dir.mkdir(parents=True, exist_ok=True)

    inp_path = write_orca_input(molecule_id, spec, work_dir, nprocs_override=nprocs)
    out_path = work_dir / f"{molecule_id}.out"
    gbw_path = work_dir / f"{molecule_id}.gbw"

    print(f"Wrote ORCA input: {inp_path}")

    if run_calculation:
        print("Running ORCA...")
        run_orca(inp_path, out_path)
        print(f"Wrote ORCA output: {out_path}")

    if not out_path.exists():
        print()
        print("Input file is ready. To run manually:")
        print(f"  cd {work_dir}")
        print(f"  orca {inp_path.name} > {out_path.name}")
        return

    orbitals = parse_orbital_energies(out_path)
    homo, lumo = determine_homo_lumo(orbitals)

    print(f"Parsed {len(orbitals)} orbitals.")
    print(f"HOMO: {homo}")
    print(f"LUMO: {lumo}")

    deck_dir = DECKS_DIR / molecule_id
    cubes_dir = deck_dir / "cubes"
    deck_dir.mkdir(parents=True, exist_ok=True)
    cubes_dir.mkdir(parents=True, exist_ok=True)

    xyz_path = deck_dir / "molecule.xyz"
    xyz_path.write_text(xyz_text(spec["name"], spec["geometry"]), encoding="utf-8")

    manifest_orbitals = []

    if export_cubes:
        if not gbw_path.exists():
            raise FileNotFoundError(
                f"Cannot find {gbw_path}. ORCA must produce a .gbw file first."
            )

        grid = int(calc.get("cube_grid", 80))

        for orb in orbitals:
            no = orb["orca_number"]
            print(f"Exporting cube for ORCA MO {no}...")

            cube_src = run_orca_plot_one(work_dir, gbw_path, no, grid)
            cube_name = f"mo_{no:03d}.cube"
            cube_dst = cubes_dir / cube_name
            shutil.copy2(cube_src, cube_dst)

            manifest_orbitals.append(
                {
                    "orca_number": no,
                    "label": f"MO {no}",
                    "role": orbital_role(no, homo, lumo),
                    "occupation": orb["occupation"],
                    "energy_hartree": orb["energy_hartree"],
                    "energy_ev": orb["energy_ev"],
                    "cube": f"cubes/{cube_name}"
                }
            )
    else:
        for orb in orbitals:
            no = orb["orca_number"]
            manifest_orbitals.append(
                {
                    "orca_number": no,
                    "label": f"MO {no}",
                    "role": orbital_role(no, homo, lumo),
                    "occupation": orb["occupation"],
                    "energy_hartree": orb["energy_hartree"],
                    "energy_ev": orb["energy_ev"],
                    "cube": f"cubes/mo_{no:03d}.cube"
                }
            )

    manifest = {
        "id": molecule_id,
        "name": spec["name"],
        "formula": spec["formula"],
        "charge": spec.get("charge", 0),
        "multiplicity": spec.get("multiplicity", 1),
        "method": calc.get("method", ""),
        "basis": calc.get("basis", ""),
        "keywords": calc.get("keywords", ""),
        "homo_orca_number": homo,
        "lumo_orca_number": lumo,
        "molecule_xyz": "molecule.xyz",
        "orbitals": manifest_orbitals,
        "symmetry": spec.get("symmetry", {})
    }

    manifest_path = deck_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8"
    )

    update_deck_index(molecule_id, manifest)

    print()
    print(f"Deck written to: {deck_dir}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("molecule_id", help="Example: methane")
    parser.add_argument("--run", action="store_true", help="Run ORCA after writing input.")
    parser.add_argument("--export-cubes", action="store_true", help="Export cube files with orca_plot.")
    parser.add_argument("--run-all", action="store_true", help="Run ORCA and export cube files.")
    parser.add_argument("--nprocs", type=int, default=None, help="Override number of ORCA processes.")

    args = parser.parse_args()

    run_calculation = args.run or args.run_all
    export_cubes = args.export_cubes or args.run_all

    build_deck(
        args.molecule_id,
        run_calculation=run_calculation,
        export_cubes=export_cubes,
        nprocs=args.nprocs
    )


if __name__ == "__main__":
    main()